name: Run les tests avant de pousser sur master

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Run Tests
        run: dotnet test Grossiste.Tests/Grossiste.Tests.csproj --no-build --verbosity normal